# Generated by Django 3.1.5 on 2021-01-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_content_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='comment',
            new_name='tmi',
        ),
        migrations.RemoveField(
            model_name='content',
            name='page',
        ),
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='content',
            name='key_line',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
