# Generated by Django 3.1.5 on 2021-01-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20210122_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='keyword',
            new_name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
